# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:
    rules:
      path: ^/ 
      priorities: [ 'json' ] 
      fallback_format: json

  body_listener: true

  param_fetcher_listener: true

  view:
    view_response_listener:  
      force: true
    formats:
      json: true

  exception:
    enabled: true
    exception_controller:  'fos_rest.exception.controller::showAction'

  routing_loader:
    default_format: json
    include_format: false

