lists:
  type: rest
  resource: App\Controller\TaskListController
  prefix: api

tasks:
  type: rest
  resource: App\Controller\TaskController
  prefix: api

notes:
  type: rest
  resource: App\Controller\NoteController
  prefix: api